// ─── B2 Upload ────────────────────────────────────────────────────────────────
// THE ONLY upload function in the entire system.
// Every module (evrak, cari, tersane) MUST use this function.
//
// Flow:
// 1. Validate file (MIME, magic bytes, size, name)
// 2. Generate object key
// 3. Upload buffer to B2 via PutObjectCommand
// 4. Log operation
// 5. Return { objectKey, fileName, fileSize, mimeType }

import { PutObjectCommand } from "@aws-sdk/client-s3";
import { getStorageClient, getBucketName } from "./client";
import { generateObjectKey } from "./object-key";
import { validateFile } from "./validation";
import { UploadError } from "./errors";
import { logUpload, logError, startTimer } from "./logger";
import type { StorageModule, UploadResult } from "./types";

// ─── Main Upload Function ─────────────────────────────────────────────────────

/**
 * Uploads a file to Backblaze B2.
 * This is the ONLY upload entry point — no other code should call PutObjectCommand.
 *
 * @param file - The File object to upload
 * @param module - Module that owns this file (evrak, cari, tersane, sirket)
 * @param entityId - Entity identifier (personelId, belgeId, etc.)
 * @param category - Sub-category (kategoriId, "fatura", etc.)
 * @param companyId - Company ID for tenant isolation
 * @param userId - Current user ID (for logging)
 *
 * @returns UploadResult with objectKey, fileName, fileSize, mimeType
 * @throws ValidationError subclasses if file fails validation
 * @throws UploadError if B2 upload fails
 */
export async function uploadToB2(params: {
  file: File;
  module: StorageModule;
  entityId: string;
  category: string;
  companyId: string;
  userId?: string;
}): Promise<UploadResult> {
  const { file, module, entityId, category, companyId, userId } = params;
  const timer = startTimer();

  // 1. Server-side validation (MIME, magic bytes, size, name)
  const validation = await validateFile(file);

  // 2. Generate standardized object key
  const objectKey = generateObjectKey({
    companyId,
    module,
    entityId,
    category,
    fileName: validation.sanitizedName,
  });

  try {
    // 3. Read file into buffer
    const arrayBuffer = await file.arrayBuffer();
    const buffer = Buffer.from(arrayBuffer);

    // 4. Upload to B2
    const client = getStorageClient();
    const bucket = getBucketName();

    const command = new PutObjectCommand({
      Bucket: bucket,
      Key: objectKey,
      Body: buffer,
      ContentType: validation.mimeType,
    });

    await client.send(command);

    // 5. Log success
    const latency = timer();
    logUpload(objectKey, userId, companyId, file.size, latency, bucket);

    return {
      objectKey,
      fileName: validation.sanitizedName,
      fileSize: file.size,
      mimeType: validation.mimeType,
    };
  } catch (error) {
    // If it's already a storage error (validation, config), re-throw
    if (error instanceof UploadError) throw error;

    // Wrap S3/network errors
    const message =
      error instanceof Error
        ? error.message
        : "Dosya yüklenirken bilinmeyen hata oluştu.";

    logError("upload", "UPLOAD_FAILED", message, objectKey, userId, companyId);

    throw new UploadError(message, {
      objectKey,
      companyId,
      originalError: String(error),
    });
  }
}

// ─── Buffer Upload (Internal) ─────────────────────────────────────────────────

/**
 * Uploads a raw buffer to B2. Used internally by template generators
 * (e.g., ozluk-generator.ts) that produce files in memory.
 *
 * This skips file validation since the buffer is generated by trusted code.
 * Do NOT expose this to external input — use uploadToB2() for user uploads.
 */
export async function uploadBufferToB2(params: {
  objectKey: string;
  buffer: Buffer;
  contentType: string;
  companyId?: string;
  userId?: string;
}): Promise<void> {
  const { objectKey, buffer, contentType, companyId, userId } = params;
  const timer = startTimer();

  try {
    const client = getStorageClient();
    const bucket = getBucketName();

    const command = new PutObjectCommand({
      Bucket: bucket,
      Key: objectKey,
      Body: buffer,
      ContentType: contentType,
    });

    await client.send(command);

    const latency = timer();
    logUpload(objectKey, userId, companyId, buffer.length, latency, bucket);
  } catch (error) {
    const message =
      error instanceof Error ? error.message : "Buffer yükleme hatası.";

    logError("upload", "BUFFER_UPLOAD_FAILED", message, objectKey, userId, companyId);

    throw new UploadError(message, {
      objectKey,
      companyId,
      originalError: String(error),
    });
  }
}
